name: peggy
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pixel_perfect: ^1.1.1
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.6.1
  google_fonts: ^4.0.3
  auto_route: ^5.0.4
  get_it: ^7.2.0
  font_awesome_flutter: ^10.4.0
  equatable: ^2.0.5
  fpdart: ^0.4.0
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  dio: ^5.0.0
  shimmer: ^2.0.0
  lottie: ^2.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  auto_route_generator: ^5.0.3
  flutter_native_splash: ^2.2.17
  freezed: ^2.3.2

flutter_native_splash:
  color: "#f2f1ed"
  image: assets/images/peggy.png

  
flutter:
  uses-material-design: true

  assets:
    - assets/ui/ # all ui design files
    - assets/icons/
    - assets/images/
    - assets/lottie/ # animations

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700